remove device param to prevent the following error.
Traceback (most recent call last):
  File "/home/user/project/GFPGAN/inference_gfpgan.py", line 180, in
<module>
    main()
  File "/home/user/project/GFPGAN/inference_gfpgan.py", line 120, in
main
    restorer = GFPGANer(
  File "/home/user/project/GFPGAN/gfpgan/utils.py", line 79, in __init__
    self.face_helper = FaceRestoreHelper(
  File "/home/user/anaconda3/envs/dreambooth/lib/python3.9/site-packages/facexlib/utils/face_restoration_helper.py",
line 99, in __init__
    self.face_det = init_detection_model(det_model, half=False,
device=self.device, model_rootpath=model_rootpath)
  File "/home/user/anaconda3/envs/dreambooth/lib/python3.9/site-packages/facexlib/detection/__init__.py",
line 10, in init_detection_model
    model = RetinaFace(network_name='resnet50', half=half,
device=device)
  File "/home/user/anaconda3/envs/dreambooth/lib/python3.9/site-packages/facexlib/detection/retinaface.py",
line 88, in __init__
    self.mean_tensor = torch.tensor([[[[104.]], [[117.]],
[[123.]]]]).to(self.device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API
call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.